language: python
sudo: true
python:
 - 3.6

branches:
  only:
  - master

addons:
  apt:
    packages:
      - gcc

env:
  - DJANGO_VERSION=1.11.5

install:
  - sudo apt-get install pngcrush
  - sudo apt-get install gifsicle
  - sudo apt-get install libjpeg-progs
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements.txt

notifications:
  email:
    on_success: never
    on_failure: always

script:
    - echo "TODO"
